import { useState, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Link2, Copy, Check, RefreshCw, HelpCircle, X, ExternalLink } from "lucide-react";
import { supabase } from "@/api/supabaseClient";
import { useLang } from "@/context/LangContext";

const INSTRUCTIONS = [
  {
    device: "iPhone / iPad",
    emoji: "🍎",
    steps: [
      "Copia o link acima",
      "Abre Definições → Calendário → Contas",
      "Toca em + Adicionar Conta → Outra",
      "Toca em Adicionar Calendário CalDAV (subscrição)",
      "Cola o link no campo Servidor e toca em Seguinte",
    ],
  },
  {
    device: "Google Calendar",
    emoji: "📅",
    steps: [
      "Copia o link acima",
      "Acede a calendar.google.com no computador",
      'Clica em "+" junto a "Outros calendários"',
      'Escolhe "A partir de URL"',
      "Cola o link e clica em Adicionar calendário",
    ],
  },
  {
    device: "Samsung / Android",
    emoji: "🤖",
    steps: [
      "Copia o link acima",
      "Abre a app Google Calendar (pré-instalada)",
      "Menu → Definições → + Adicionar calendário",
      "Escolhe subscrição por URL e cola o link",
    ],
  },
  {
    device: "Xiaomi / MIUI",
    emoji: "📱",
    steps: [
      "Copia o link acima",
      "Abre Definições → Contas → Google → Calendário",
      "Ou usa a app Google Calendar (recomendado)",
      "Cola o link em Adicionar calendário por URL",
    ],
  },
  {
    device: "Huawei",
    emoji: "📲",
    steps: [
      "Copia o link acima",
      "Instala Google Calendar da Huawei AppGallery",
      "Menu → Definições → Adicionar calendário",
      "Escolhe subscrição por URL e cola o link",
    ],
  },
];

export default function ICalFeed() {
  const { t } = useLang();
  const [token, setToken] = useState(null);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [copied, setCopied] = useState(false);
  const [showHelp, setShowHelp] = useState(false);

  const supabaseUrl = import.meta.env.VITE_SUPABASE_URL || "";
  const feedUrl = token ? `${supabaseUrl}/functions/v1/ical-feed?token=${token}` : "";

  useEffect(() => {
    loadToken();
  }, []);

  const loadToken = async () => {
    setLoading(true);
    try {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) return;
      const { data } = await supabase
        .from("ical_tokens")
        .select("token")
        .eq("user_id", user.id)
        .single();
      if (data) setToken(data.token);
    } finally {
      setLoading(false);
    }
  };

  const generate = async () => {
    setGenerating(true);
    try {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) return;
      // Upsert — creates or keeps existing token
      const { data } = await supabase
        .from("ical_tokens")
        .upsert({ user_id: user.id }, { onConflict: "user_id" })
        .select("token")
        .single();
      if (data) setToken(data.token);
    } finally {
      setGenerating(false);
    }
  };

  const regenerate = async () => {
    if (!window.confirm("Regenerar link? O link antigo deixará de funcionar.")) return;
    setGenerating(true);
    try {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) return;
      // Delete old → insert new (new token UUID generated by DB)
      await supabase.from("ical_tokens").delete().eq("user_id", user.id);
      const { data } = await supabase
        .from("ical_tokens")
        .insert({ user_id: user.id })
        .select("token")
        .single();
      if (data) setToken(data.token);
    } finally {
      setGenerating(false);
    }
  };

  const copy = () => {
    navigator.clipboard.writeText(feedUrl).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  };

  if (loading) return <div className="px-4 py-3 text-xs text-muted-foreground">A carregar…</div>;

  return (
    <>
      <div className="px-4 py-3 space-y-3">
        {!token ? (
          <div className="flex items-center gap-3">
            <p className="text-xs text-muted-foreground flex-1">
              Gera um link privado para subscrever o teu calendário em qualquer dispositivo.
              Atualiza de 30 em 30 minutos.
            </p>
            <button
              onClick={generate}
              disabled={generating}
              className="flex items-center gap-1.5 px-3 py-2 rounded-xl bg-[#E87A5A] text-white text-xs font-semibold hover:bg-[#D4694A] transition-all disabled:opacity-50"
            >
              <Link2 className="w-3.5 h-3.5" />
              {generating ? "A gerar…" : "Gerar link"}
            </button>
          </div>
        ) : (
          <>
            <div className="flex items-center gap-2 bg-secondary/50 rounded-xl px-3 py-2 border border-border">
              <p className="flex-1 text-[10px] font-mono text-muted-foreground truncate">{feedUrl}</p>
              <button onClick={copy} className="flex-shrink-0 w-7 h-7 rounded-lg bg-white border border-border flex items-center justify-center hover:border-[#E87A5A]/40 transition-all">
                {copied ? <Check className="w-3.5 h-3.5 text-emerald-500" /> : <Copy className="w-3.5 h-3.5 text-muted-foreground" />}
              </button>
            </div>
            <div className="flex items-center gap-2">
              <p className="text-[10px] text-muted-foreground flex-1">
                Subscreve este link no teu calendário. Atualiza a cada 30 minutos.
              </p>
              <button onClick={() => setShowHelp(true)} className="flex items-center gap-1 text-[10px] text-[#E87A5A] font-medium hover:underline">
                <HelpCircle className="w-3 h-3" /> Como adicionar?
              </button>
              <button onClick={regenerate} disabled={generating} className="w-7 h-7 rounded-lg bg-secondary border border-border flex items-center justify-center hover:bg-border transition-all" title="Regenerar link">
                <RefreshCw className={`w-3.5 h-3.5 text-muted-foreground ${generating ? "animate-spin" : ""}`} />
              </button>
            </div>
          </>
        )}
      </div>

      {/* Help modal */}
      <AnimatePresence>
        {showHelp && (
          <motion.div
            initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
            className="fixed inset-0 bg-black/30 backdrop-blur-sm z-[70] flex items-end sm:items-center justify-center p-4"
            onClick={() => setShowHelp(false)}
          >
            <motion.div
              initial={{ y: 40, opacity: 0 }} animate={{ y: 0, opacity: 1 }} exit={{ y: 40, opacity: 0 }}
              transition={{ type: "spring", damping: 25, stiffness: 220 }}
              onClick={(e) => e.stopPropagation()}
              className="bg-white rounded-3xl w-full max-w-md max-h-[85vh] overflow-y-auto shadow-2xl"
            >
              <div className="sticky top-0 bg-white rounded-t-3xl px-5 pt-5 pb-3 flex items-center justify-between border-b border-border">
                <div>
                  <h2 className="text-base font-bold text-foreground">Como adicionar ao calendário</h2>
                  <p className="text-[11px] text-muted-foreground mt-0.5">Copia o link e segue os passos para o teu dispositivo</p>
                </div>
                <button onClick={() => setShowHelp(false)} className="w-8 h-8 rounded-full bg-secondary flex items-center justify-center">
                  <X className="w-4 h-4" />
                </button>
              </div>

              {/* Quick copy */}
              <div className="px-5 py-3 border-b border-border">
                <div className="flex items-center gap-2 bg-secondary/50 rounded-xl px-3 py-2">
                  <p className="flex-1 text-[10px] font-mono text-muted-foreground truncate">{feedUrl}</p>
                  <button onClick={copy} className="flex-shrink-0 flex items-center gap-1 px-2 py-1 rounded-lg bg-[#E87A5A] text-white text-[10px] font-semibold">
                    {copied ? <><Check className="w-3 h-3" /> Copiado</> : <><Copy className="w-3 h-3" /> Copiar</>}
                  </button>
                </div>
              </div>

              <div className="px-5 py-4 space-y-5">
                {INSTRUCTIONS.map((inst) => (
                  <div key={inst.device}>
                    <div className="flex items-center gap-2 mb-2">
                      <span className="text-lg">{inst.emoji}</span>
                      <h3 className="text-sm font-bold text-foreground">{inst.device}</h3>
                    </div>
                    <ol className="space-y-1">
                      {inst.steps.map((step, i) => (
                        <li key={i} className="flex items-start gap-2 text-xs text-muted-foreground">
                          <span className="flex-shrink-0 w-4 h-4 rounded-full bg-[#E87A5A]/10 text-[#E87A5A] text-[10px] font-bold flex items-center justify-center mt-0.5">{i + 1}</span>
                          {step}
                        </li>
                      ))}
                    </ol>
                  </div>
                ))}
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </>
  );
}
